//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopCosmetic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public int idBasket { get; set; }
        public int numberOrder { get; set; }
        public int product { get; set; }
        public int amount { get; set; }
        public decimal finalPrice { get; set; }
        public int lack { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
